# kind-cluster-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 30001 # kind's docker container internal port 
      hostPort: 30001 # maps kind's conatiners port to laptops's 30001
  - role: worker
  - role: worker
