apiVersion: apps/v1 # Kubernetes API version for Deployment objects
kind: Deployment # Type of Kubernetes resource (Deployment)
metadata:
  name: nginx-deployment # Name of the Deployment
  namespace: argocd # Namespace where the Deployment will be created
  labels: # Labels for the Deployment
    app: argocdapp # Label key-value pair for identifying the Deployment
spec:
  replicas: 3 # Number of Pod replicas to create (3 in this case)
  selector: # Defines how the Deployment finds Pods to manage
    matchLabels: # Labels used to match Pods
      app: argocdapp # Pods with this label will be managed by this Deployment
  template: # Template for creating Pods
    metadata:
      labels: # Labels assigned to the Pods
        app: nginx # Pods will have this label
    spec: # Specification for the Pod's containers
      containers: # List of containers in the Pod
        - name: nginx # Name of the container
          image: nginx:1.14.2 # Docker image to use for the container
          ports: # List of ports to expose from the container
            - containerPort: 80 # Nginx listens on port 80
