apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  labels:
    app: argocdapp
spec:
  rules:
    - host: nextapp.arpan
      http:
        paths:
          - path: /hello
            pathType: Prefix
            backend:
              service:
                name: argocd-service
                port:
                  number: 8000
